# https://taskfile.dev

version: '3'

vars:
  PROJECT: ontv-mac
  SCHEME: ontv
  APPMAME: ontv
  BUNDLE: net.cacko.ontv

tasks:
  push:
    desc: push code
    cmds:
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)"
      - git push

  init:
    desc: install pods
    cmds:
      - gem install cocoapods
      - pod install
      - poetry install
      - npm install

  archive:
    desc: build application
    cmds:
      - echo "increment build number"
      - agvtool next-version -all
      - echo "building app"
      - xcodebuild clean
      - xcodebuild  ARCHS=arm64 ONLY_ACTIVE_ARCH=NO -workspace ontv.xcworkspace -scheme {{.SCHEME}} -configuration Release DSTROOT="/Users/jago/Code/{{.PROJECT}}" archive

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMS"
      - rm -f ontv-arm64.dmg
      - ./node_modules/.bin/appdmg ontv.json ontv-arm64.dmg

  install:
    desc: copy new app localy
    cmds:
      - echo "copy app to /Applications"
      - rm -rf /Applications/onTV.app || true
      - mv Applications/onTV.app /Applications 

  publish:
    desc: publish dmg file as package
    cmds:
      - echo "publishing app to github"
      - mamba run --live-stream -n {{.PROJECT}} python -m deploy {{.CLI_ARGS}}

  uncacheimages:
    desc: removes app images cache
    cmds:
      - rm -rf ~/Library/Containers/{{.BUNDLE}}/Data/Library/Caches/*

  uncache:
    desc: delete app container
    cmds:
      - rm -rf ~/Library/Containers/{{.BUNDLE}}

  fix:
    desc: fix formatter
    cmds:
      - /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode.app


  release:
    desc: archive, dmg and upload package
    cmds:
      - task: push
      - task: archive
      - task: dmg
      - task: publish
      - task: install
