# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  push:
    desc: push code
    cmds:
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)"
      - git push

  init:
    desc: install pods
    cmds:
      - gem install cocoapods
      - pod install
      - poetry install
      - npm install

  archive:
    desc: build application
    cmds:
      - echo "increment build number"
      - agvtool next-version -all
      - echo "building app"
      - xcodebuild clean
      - xcodebuild  ARCHS=arm64 ONLY_ACTIVE_ARCH=NO -workspace ontv.xcworkspace -scheme ontv -jobs 4 -configuration Release DSTROOT="/Users/jago/Code/ontv-mac" archive

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMS"
      - rm -f *.dmg
      - ./node_modules/.bin/appdmg ontv.json ontv-arm64.dmg

  install:
    desc: copy new app localy
    cmds:
      - echo "copy app to /Applications"
      - rm -rf /Applications/ontv.app
      - mv Applications/ontv.app /Applications

  publish:
    desc: publish dmg file as package
    cmds:
      - echo "publishing app to gitlab"
      - poetry run python -m deploy {{.CLI_ARGS}}

  uncacheimages:
    desc: removes app images cache
    cmds:
      - rm -rf ~/Library/Containers/net.cacko.ontv/Data/Library/Caches/*

  uncache:
    desc: delete app container
    cmds:
      - rm -rf ~/Library/Containers/net.cacko.ontv

  fix:
    desc: fix formatter
    cmds:
      - /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode.app


  release:
    desc: archive, dmg and upload package
    cmds:
      - task: archive
      - task: dmg
      - task: publish
      - task: install
