# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  push:
    desc: push code
    cmds:
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)"
      - git push

  init:
    desc: install pods
    cmds:
      - gem install cocoapods
      - pod install

  archive:
    desc: build application
    cmds:
      - echo "increment build number"
      - agvtool next-version -all
      - echo "building app"
      - xcodebuild -workspace craptv.xcworkspace -scheme craptv -configuration Release DSTROOT="/Users/jago/Code/craptv" archive

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMS"
      - rm -f craptv.dmg
      - appdmg craptv.json craptv.dmg

  install:
    desc: copy new app localy
    cmds:
      - echo "copy app to /Applications"
      - rm -rf /Applications/craptv.app
      - mv Applications/craptv.app /Applications

  publish:
    desc: publish dmg file as package
    cmds:
      - echo "publishing app to gitlab"
      - poetry run python deploy.py

  release:
    desc: archive, dmg and upload package
    cmds:
      - task: archive
      - task: dmg
      - task: publish
      - task: push
      - task: install
