# https://taskfile.dev

version: '3'

vars:
  PROJECT: ontv-mac
  SCHEME: ontv
  APPMAME: ontv
  BUNDLE: net.cacko.ontv

tasks:
  push:
    desc: push code
    cmds:
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push

  init:
    desc: install pods
    cmds:
      - gem install cocoapods
      - pod install
      - poetry install
      - npm install

  archive:
    desc: build application
    cmds:
      - echo "increment build number"
      - agvtool next-version -all
      - echo "building app"
      - xcodebuild clean
      - mkdir -p ./Applications
      - xcodebuild  ARCHS=arm64 ONLY_ACTIVE_ARCH=NO -workspace ontv.xcworkspace -scheme ontv -configuration Release DSTROOT="/Users/jago/Code/ontv-mac" archive || true

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMG"
      - rm -f "ontv-arm64.dmg" || true
      - create-dmg --volname "onTV" --volicon "icon.icns" --window-pos 200 120 --window-size 800 400   --icon-size 100   --icon "onTV.app" 200 190   --hide-extension "onTV.app"   --app-drop-link 600 185   "ontv-arm64.dmg" Applications/ontv.app
  install:
    desc: copy new app localy
    cmds:
      - echo "copy app to /Applications"
      - rm -rf /Applications/onTV.app || true
      - mv -f Applications/onTV.app /Applications 

  publish:
    desc: publish dmg file as package
    cmds:
      - echo "publishing app to github"
      - mamba run --live-stream -n {{.PROJECT}} python -m deploy {{.CLI_ARGS}}

  uncacheimages:
    desc: removes app images cache
    cmds:
      - rm -rf ~/Library/Containers/{{.BUNDLE}}/Data/Library/Caches/*

  uncache:
    desc: delete app container
    cmds:
      - rm -rf ~/Library/Containers/{{.BUNDLE}}

  fix:
    desc: fix formatter
    cmds:
      - /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode.app


  release:
    desc: archive, dmg and upload package
    cmds:
      - task: push
      - task: archive
      - task: dmg
      - task: publish
      - task: install
